### ISSUE TITLE
عدم اتصال به زرین پال

### ISSUE THREAD

**Issue by alinasiri1367** [PoolPort/PoolPort#23]
سلام
من تموم مراحل رو به درستی انجام دادم و وقتی دکمه پرداخت رو میزنم هیچ اتفاقی نمی افتد و فقط یک رکورد به جدول transactions
 اضافه میشه؟

**Comment by m-jch** [comment]
سلام
آیا از فریم ورک خاصی استفاده میکنید؟

**Comment by alinasiri1367** [comment]
آره 
از لاراول 5.1 استفاده می کنم

**Comment by m-jch** [comment]
میتونید قسمتی که کدهای مربوط به 
PoolPort
رو نوشتید اینجا بزارید؟

**Comment by alinasiri1367** [comment]
`Route::get('/testbank',function(){
		$poolPort = new PoolPort(PoolPort::P_ZARINPAL);
		try {
			$refId = $poolPort->set(1000)->ready()->refId();
			// Your code here
			$poolPort->redirect();
		} catch (Exception $e) {
			echo $e->getMessage();
		}
	});`
اینم فایل تنظیمات : 
`'zarinpal' => array(
			'merchant-id'  => '؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟',
			'type'         => 'zarin-gate',                           // Types: [zarin-gate || normal]
			'callback-url' => 'http://www.test.ir',
			'server'       => 'germany',                              // Servers: [germany || iran]
			'email'        => 'alinasiri1367@gmail.com',
			'mobile'       => '09000000',
			'description'  => 'description :)',
		),`

**Comment by m-jch** [comment]
فکر کنم شما باید خط زیر رو
‍‍
```
$poolPort->redirect();
```

به

```
return $poolPort->redirect();
```

تغییر بدید. که البته مشکل از مستندات است که داخلش ذکر نشده

**Comment by alinasiri1367** [comment]
پس کلآ این پکیج برای لاراول نیست؟؟

**Comment by m-jch** [comment]
خیر، شما میتونید هرکجا که بخواید ازش استفاده کنید.

**Comment by m-jch** [comment]
اگر مشکلتون فقط در این زمینه رفع شده، لطفا این
issue
رو ببندید یا پیام بگذارید.
