### ISSUE TITLE
درگاه بانک ملت خطای 42 برمی گردونه 

### ISSUE THREAD

**Issue by nasservb** [PoolPort/PoolPort#25]
سلام و تشکر فراوان بابت افزونه بسیار خوبتون 
من درگاه ملی رو بدون مشکل استفاده کردم . 
ولی همون کد برای ملت خطای 42 بر می گردونه  .

**Comment by m-jch** [comment]
سلام، خیلی ممنون
توی درگاه ملت مشکل دارین یا پارسیان؟
چون داخل گیتر فکر کنم نوشته بودین پارسیان

**Comment by nasservb** [comment]
من با ملت مشکل دارم

**Comment by m-jch** [comment]
#26

**Comment by m-jch** [comment]
Referenced on #26
