### ISSUE TITLE
"Could not connect to host" error

### ISSUE THREAD

**Issue by Anisi** [PoolPort/PoolPort#30]
Hello
When I want to connect to "mellat gateway", after a delay, almost always the error "Could not connect to host" occurs.
I googled it and I couldn't find a proper solution, but i realized that it is related to soap library.
What should I do?
Thanks

**Comment by shahryarjb** [comment]
من این مشکل رو روی نسخه پی اچ پی ۵.۶ داشتم روی نسخه ۵.۵ نداشتم 
فکر می کنم مشکل از سرور باشه.

**Comment by Anisi** [comment]
Hello
Thanks for your attention.
I apprised mellat support agent and they confessed that the problem is on their side. The problem is fixed now.

**Comment by Anisi** [comment]
Hello
Thanks for your attention.
I apprised Mellat support agent and they confessed that the problem is on their side. The problem is fixed now.
