### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by MohammadReza10** [PoolPort/PoolPort#32]
داداش چند روزیه این ایراد رو میده
جریان رو میدونی ؟

**Comment by m-jch** [comment]
سلام، ببخشید دیر جواب دادم، سربازی بودم و هستم البته
برای کدوم درگاه این خطا داده میشه؟

**Comment by MohammadReza10** [comment]
سلام
خواهش میکنم 
مشکل به خاطر اپدیت نبودن وب سرویس شاپرک به ورژن 7.1 هستش و تمامی بانک ها همین مشکل رو دارن
