### ISSUE TITLE
مشکل در ConfigFileNotFoundException

### ISSUE THREAD

**Issue by rrreza** [PoolPort/PoolPort#34]
با درود
پکیج فوق العاده مثبت شما را بر روی لاراول نصب کردم. 
دقیقا مشابه راهنما آن را نصب کردم ولی متاسفانه ایرادی پیش می آمد و پرداخت انجام نمی شد لطفا راهنمایی بفرمایید.
ایراد را از ConfigFileNotFoundException اعلام می کند.
لاراول خام و دسته اول بصورت لوکال نصب گردیده است
نسخه لاراول 5.5
نسخه php 7.15
با تشکر
    protected function load()
    {
        if (is_file($this->filePath)) {
            $this->config = require $this->filePath;
            return true;
        }
        else if(is_file($this->defaultFilePath)) {
            $this->config = require $this->defaultFilePath;
            return true;
        }
 
        throw new ConfigFileNotFoundException;
    }
}

**Comment by m-jch** [comment]
شما باید فایل کانفیگ را کنار پوشه
vendor
قرار بدین تا به صورت خودکار لود بشه و یا اینکه در زمان ساخت شی آدرس فایل کانفیگ رو خودتون بهش بدین

**Comment by m-jch** [comment]
من الان تست کردم و مشکلی نبود، اگر کدی که استفاده میکنید رو بفرستید شاید بیشتر بتونم کمک کنم
