### ISSUE TITLE
رفع مشکل از زررین پال

### ISSUE THREAD

**Issue by nasservb** [PoolPort/PoolPort#39]
با سلام واحترام
تشکر از کار بسیار عالی تون 
من امروز روی درگاه زرین ال چند با تست کردم که خطای زیر رو می داد 
`SoapClient::SoapClient(): Invalid parameters`

بعد از کمی تحقیق متوجه شدم وب سرور اس اس ال نداره و نمی تونه به آدرس 
https  
دسترسی پیدا کنه 
این خطا رو می داد 
`Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from`
افزونه رو هم فعال کردم دسترسی به آدرس زرین پال درست شد ولی پرداخت  باز درست نشد . 

کمی اسکریپت های خود زرین پال رو چک کردم 
دیدم شما موقع ساخت کلاینت سوآپ خیلی پارامتر اضافه می فرستید به سرور زرین پال در این خط 
`$soap = new SoapClient($this->serverUrl, $this->config);`

وقتی محتوای 
$this->config
 رو چاپ کردم به این گزینه شک کردم 
در مستندات زرین پال اینطور استفاده کرده 
`$client = new SoapClient('https://www.zarinpal.com/pg/services/WebGate/wsdl', ['encoding' => 'UTF-8']);`

دقیقآ اشکال از همین جا بود 
 و با تغییر خط 
`$soap = new SoapClient($this->serverUrl, $this->config);`
به خط 
`$soap = new SoapClient($this->serverUrl, ['encoding' => 'UTF-8']);`

مشکل حل شد .

**Comment by khanzadimahdi** [comment]
use below package in laravel 

https://github.com/shetabit/payment

**Comment by baamirreza** [comment]
سلام منم امروز موقع پرداخت این ارور رو میگیرم ،از یه افزونه صورتحساب استفاده میکنم،تا دیشب تست میگرفتم وارد درگاه پرداخت میشد ولی از امروز خطارو میگیرم:

Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://zarinpal.com/pg/services/WebGate/wsdl' : Premature end of data in tag html line 1

با هاست و پشتیبانی صحبت کردم ولی فایده ای نداشت.مشکل از کجا میتونه باشه،اگه راهنماییم کنید ممنون میشم

**Comment by m-jch** [comment]
سلام لطفا از آخرین نسخه استفاده کنید، نسخه v3.8.0
زرین پال بروز شده و نباید مشکلی باشه. و لطفا نتیجه رو اعلام کنید
