### ISSUE TITLE
package cant install

### ISSUE THREAD

**Issue by firoouze** [PoolPort/PoolPort#40]
[RuntimeException]                                                      
  /app/vendor/poolport/poolport does not exist and could not be created

**Comment by m-jch** [comment]
سلام
خیلی جالبه
شما به چه صورت از پکیج استفاده میکنید؟
با کامپوسر استفاده میکنید؟

**Comment by firoouze** [comment]
سلام
درست شد . ممنون از پیگیری سریعتون
