### ISSUE TITLE
مشکل در دریافت refID قبل ار ارسال به بانک

### ISSUE THREAD

**Issue by love4php** [PoolPort/PoolPort#41]
با سلام و تشکر بابت بسته خوبی که آماده کردید ؛ 
بسته شما را بصورت کامل استفاده نکردم و بسته را در قسمت بانک پاسارگاد استفاده کردم  ؛ 
دو مطلب بود که دوست داشتم خدمتتون بگم که انشالله بسته بدون مشکلی داشته باشید
1- refId قبل از ارسال به بانک قابل دسترسی نیست و فقط در فرم از آن استفاده شده 
2- آدرس ریدایرکت علاوه بر اینکه در کانفیگ قید شده بتوان در لحطه نیز اون و عوض کرد ؛ ممکن است پروژه ها مانند پروژه من از مازول های متفاوتی استفاده کند 

مطلب اول به شدت حیاتی بوده ولی مطلب دوم جهت انعطاف بیشتر 

با تشکر

**Comment by m-jch** [comment]
سلام خیلی ممنون
بانک پاسارگاد همونطور که در مستندات ذکر شده به صورت کامل پیاده سازی نشده و اگر شما تمایل دارین که این درگاه رو تکمیل کنید خیلی خوشحال میشیم

مقدار refId
به صورت زیر قبل از ریدایرکت به بانک قابل دسترسی هست:
```
$refId = $poolPort->set($price)->ready()->refId();
```

آدرس ریدایرکت رو توسط متد
setConfig
میتونید به ازای هر درگاه عوض کنید به صورت زیر:
```
$poolPort = new PoolPort(PoolPort::P_MELLAT);
$poolPort->setConfig('mellat.callback-url', 'another url');
```

و یا میتونید با استفاده از تابع 
setGlobalCallbackUrl
آدرس همه درگاه‌ها رو عوض کنید
```
$port = new PoolPort(PoolPort::P_SIMULATOR);
$port->setGlobalCallbackUrl('another url');
```
