### ISSUE TITLE
خطای بانک سامان

### ISSUE THREAD

**Issue by mortezash** [PoolPort/PoolPort#47]
سلام.خسته نباشین.من موقع برگشت از درگاه بانک.برای بانک سامان  خطای Undefined variable $stateCode میده.
ErrorException {#766 ▼
  #message: "Undefined variable $stateCode"
  #code: 0
  #file: "/home/tourgardan/domains/dev2.afraitn.com/public_html/laravel/vendor/poolport/poolport/src/Saman/Saman.php"
  #line: 178
  #severity: E_WARNING
  trace: {▶}
}

**Comment by m-jch** [comment]
درگاه بانک سامان بروز شد. لطفا به نسخه 3.8.1 آپدیت کنید.
